# Generated by Django 4.1.13 on 2023-11-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('body', models.TextField()),
            ],
        ),
    ]
