# Generated by Django 4.0 on 2023-12-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/empty_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
